name: sff_lib
description: Small package designed to simplify working with files/directories.
version: 0.0.1
repository: https://github.com/yuraMovsesyan/sff_lib

environment:
  sdk: ^3.2.6

dependencies:
  async: ^2.11.0
  path: ^1.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
